### ISSUE TITLE
Build instructions and tests

### ISSUE THREAD

**Issue by filmaj** [blackberry/WebWorks#3]
I would love to contribute to this project so I can fix a bunch of issues.
1. How do I build it?
2. Do you have a test suite I can run to make sure I don't break stuff?

**Comment by tneil** [comment]
Hi filmaj,

We are currently working on the build scripts and test suite that we can upload.  We have all the test environments internally, we are just refactoring them so that they can be easily setup and run by the community

**Comment by mwbrooks** [comment]
Hey Tim,

I have an ANT script that builds the WebWorks SDK. It's partially thrown together, because I still need to use files that are only available in the SDK release. Regardless, it creates a working `bbwp.jar`.

If you have something in the works, I don't see much point in sending a pull request. If you think there's value, then I can publicly release it in some form.

Michael

**Comment by tneil** [comment]
Hi Michael,

Let me talk with the team.  We currently have a Maven build process that we are working on getting pushed up to the repository.  I'll check to see the timing on when this will be uploaded.  Our scripts also have a bunch of integration with our Java unit tests as well as yUI JavaScript unit tests.

We are only a couple of days away from posting up our contributor's agreement as well that will allow us to accept external contributions.  So we'll need to make sure we have that in place before we could accept your scripts.

I'll post back with some more details

**Comment by tneil** [comment]
I talked with the Dev team and they have a bunch of Maven work that they will be getting up into the project ASAP.

Also, we now have our contributor's agreements in place

https://github.com/blackberry/WebWorks/wiki/How-To-Contribute

**Comment by mwbrooks** [comment]
Tim,

Sounds good. I wouldn't bother the world with my tossed together ANT scripts.

Great to see that you guys have a CA up now and we're looking forward to seeing those Java unit tests!

Michael

**Comment by tneil** [comment]
You'll be able to see both Java and JavaScript unit tests.. and ActionScript unit tests for the Tablet OS version of the SDK too :)

**Comment by tneil** [comment]
Hi Fil,

If you take a look at my "restructure" branch you'll see where we are heading for the structure of the repo.  I have started to include some build instructions there. The build instructions still need some work.

https://github.com/tneil/WebWorks/tree/restructure

I have also restructured the source folders so that it is easy to patch your latest build of WebWorks with whatever branch you desire off of the repo.  

We'll be making these changes in the main repository shortly

**Comment by tneil** [comment]
I'm happy to say that we have now added our build scripts so I'm closing this issue... giddy-up

**Comment by filmaj** [comment]
Holy sh*t - nice work!

Going to have to find some time to play around with building my own!

**Comment by mwbrooks** [comment]
Yep nice work guys!

I compiled the SDK on the weekend using OS X. I had to alter a few scripts to get it running. They were minor changes (backslash to forward-slash). Has anyone else seen this issue? I can provide more detail if you'd like.

Michael

**Comment by tneil** [comment]
Yes.. Please do find any issues that you are finding.. I know we have had some "glitches" on Mac but I would like to hear what you ran into.
