### ISSUE TITLE
Back Button issues on BB6

### ISSUE THREAD

**Issue by tneil** [blackberry/WebWorks#56]
There seems to be a bunch of inconsistencies with the hardware back button and how it reacts in BrowserField.  There are issues where it doesn't recognize navigation through anchor tags as well as not being able to work properly if someone sets the **location.href** through JavaScript

Some early tests show that if we were to actually call javascript **history.back()** instead of calling the back method on BrowserField that it resolves some of these issues.

This doesn't seem to be a problem on BB5.

**Comment by tohman** [comment]
The issue can’t be eliminated because its root is in **BrowserField** to where the call to go back in history is delegated.  The issue appears when redirecting pages using **location.href**. The issue wasn't experienced when **Anchor** was used for page redirection.

Because **location.href** in BB6 doesn't  cause the new entry to the browser history, use **Anchor** instead to eliminate the issue, or alternatively trap the back button in JavaScript and call **history.back()** (history.back might not work on all devices).

**Comment by kwallis** [comment]
We can't use history.back() in the template code?

**Comment by tohman** [comment]
If we use that then the BrowserFieldHistory would be out of sync, and won't be able to identify always correct if there is still pages to go back or to close the app when there is no pages in the history.

**Comment by kwallis** [comment]
Tim, any additional thoughts before we close this issue?

----- Original Message -----

**Comment by tneil** [comment]
So if you do a history.back() in JavaScript it doesn't update the BrowserField history?

**Comment by tohman** [comment]
It doesn't. 
If I move forward 4 times from page 1 to page 5 and 2 backward with history.back that brings me to page 3, then calling to goBack() method on BrowserFieldHistory would bring me to page 4 (down from 5) and next call to history.back() would bring me to page 3 again.
